<?php

namespace App\Services;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

/**
 * EDS HUB Completed Application Sync Service
 *
 * Dispatches completed website registration applications to EDS HUB CRM
 * server-to-server immediately following a successful local registration.
 *
 * Provides a more reliable server-to-server completion sync, immune to
 * client-side network interruptions, browser tab closure, or ad blockers.
 *
 * CRITICAL PRIVACY & SECURITY RULES:
 * - NEVER forward medical conditions, dietary restrictions, or health data.
 * - NEVER forward passport, dental license files, or emergency contact.
 * - NEVER forward digital signatures or raw request payloads.
 * - NEVER log customer email, phone, name, or raw response bodies.
 * - Non-blocking: failures must log a technical warning and NEVER interrupt student registration.
 */
class EdsHubSyncService
{
    private const EDS_SUBMIT_URL = 'https://xogcexclqiornuscsdmn.supabase.co/functions/v1/submit-public-form';
    private const FORM_SLUG = 'website-register';
    private const PUBLIC_ANON_KEY = 'sb_publishable_AyrxHrDnvNXwKvk1kBDqng_TgqHMPdw';
    private const TIMEOUT_SECONDS = 5;

    /**
     * Dispatch completed form submission to EDS HUB.
     * Call this method from your RegistrationController AFTER your database transaction commits.
     *
     * @param Request $request The incoming validated HTTP request.
     * @return bool True if synced successfully, false otherwise (failure is non-fatal).
     */
    public static function syncCompletedApplication(Request $request): bool
    {
        try {
            // 1. Retrieve the attempt ID generated by the frontend script
            $attemptId = $request->input('eds_form_attempt_id');
            if (empty($attemptId)) {
                $attemptId = 'reg_' . (string) Str::uuid();
            }

            // 2. Derive stable, deterministic idempotency key for this attempt
            // Guarantees retries of the SAME application reuse the exact same idempotency key
            // (Uses safe technical attempt ID hash, zero personal data involved)
            $idempotencyKey = 'comp_' . substr(hash('sha256', 'eds_app_sync_' . $attemptId), 0, 32);

            // 3. Prepare STRICTLY SANITIZED CRM whitelist payload
            // Do NOT include medical, dietary, documents, signature, or emergency contacts.
            $payload = [
                'slug' => self::FORM_SLUG,
                'idempotency_key' => $idempotencyKey,
                'external_attempt_id' => $attemptId,
                'fields' => [
                    'name' => trim((string) $request->input('name')),
                    'email' => trim((string) $request->input('email')),
                    'phone' => trim((string) $request->input('phone')),
                    'course' => trim((string) $request->input('course')),
                    'specialty' => $request->filled('specialty') ? trim((string) $request->input('specialty')) : null,
                    'years_in_practice' => $request->filled('years_in_practice') ? trim((string) $request->input('years_in_practice')) : null,
                    'surgical_experience' => $request->filled('surgical_experience') ? trim((string) $request->input('surgical_experience')) : null,
                    'agd_number' => $request->filled('agd_number') ? trim((string) $request->input('agd_number')) : null,
                    'heard_from' => $request->filled('heard_from') ? trim((string) $request->input('heard_from')) : null,
                    'referral_name' => $request->filled('referral_name') ? trim((string) $request->input('referral_name')) : null,
                    'promo_code' => $request->filled('promo_code') ? trim((string) $request->input('promo_code')) : null,
                    'terms_accepted' => true, // Confirmed on successful application
                ],
            ];

            // 4. Remove null fields to keep payload compact
            $payload['fields'] = array_filter($payload['fields'], fn ($value) => $value !== null && $value !== '');

            // 5. Send non-blocking HTTP request with short timeout
            $response = Http::timeout(self::TIMEOUT_SECONDS)
                ->withHeaders([
                    'Content-Type' => 'application/json',
                    'apikey' => self::PUBLIC_ANON_KEY,
                ])
                ->post(self::EDS_SUBMIT_URL, $payload);

            if ($response->successful()) {
                // Log safe technical telemetry ONLY (no email, phone, name, or payload)
                Log::info('[EDS HUB] Completed application synced successfully.', [
                    'attempt_id' => $attemptId,
                    'status' => $response->status(),
                ]);
                return true;
            }

            // Log technical error status ONLY (do not dump remote response body)
            Log::warning('[EDS HUB] Completed application sync returned non-200.', [
                'status' => $response->status(),
                'attempt_id' => $attemptId,
            ]);
            return false;

        } catch (\Throwable $e) {
            // Guarantee registration flow is NEVER interrupted by CRM connectivity issues
            Log::warning('[EDS HUB] Completed application sync failed (non-fatal): ' . $e->getMessage(), [
                'exception' => get_class($e),
                'attempt_id' => $request->input('eds_form_attempt_id'),
            ]);
            return false;
        }
    }
}
